opengl: Makefile.am: remove emscripten specific gles2 libraries
75b62f44d8d08aac581e67dea4b4658b3736ce9f aims to generalize
HAVE_GLES2 with the introduction of (!HAVE_GL and HAVE_GLES2)
and removes android specific library adding.

However, emscripen, like android falls into this criteria but not
removed. Hence libraries like libvlc_opengles.la is added twice and
causing error: "duplicate symbol" during shared module building.

Fix this by removing emscripten's block of code that causes this.