vlc_media_library.h: include missing time.h
On MacOS, the checkheader for vlc_media_library.h fails with:

    In file included from checkheader_vlc_media_library_h.c:3:
    /Users/unidan/Workspace/vlc/extras/package/macosx/../../../include/vlc_media_library.h:151:5: error: unknown type name 'time_t'; did you mean 'size_t'?
        time_t i_last_modification_date;
        ^~~~~~
        size_t
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_size_t.h:31:32: note: 'size_t' declared here
    typedef __darwin_size_t        size_t;
                                   ^
    In file included from checkheader_vlc_media_library_h.c:3:
    /Users/unidan/Workspace/vlc/extras/package/macosx/../../../include/vlc_media_library.h:213:5: error: unknown type name 'time_t'; did you mean 'size_t'?
        time_t i_last_played_date;
        ^~~~~~
        size_t
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_size_t.h:31:32: note: 'size_t' declared here
    typedef __darwin_size_t        size_t;
                                   ^
    In file included from checkheader_vlc_media_library_h.c:3:
    /Users/unidan/Workspace/vlc/extras/package/macosx/../../../include/vlc_media_library.h:257:5: error: unknown type name 'time_t'; did you mean 'size_t'?
        time_t i_creation_date;
        ^~~~~~
        size_t
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_size_t.h:31:32: note: 'size_t' declared here
    typedef __darwin_size_t        size_t;
                                   ^
    In file included from checkheader_vlc_media_library_h.c:3:
    /Users/unidan/Workspace/vlc/extras/package/macosx/../../../include/vlc_media_library.h:258:5: error: unknown type name 'time_t'; did you mean 'size_t'?
        time_t i_last_modification_date;
        ^~~~~~
        size_t
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_size_t.h:31:32: note: 'size_t' declared here
    typedef __darwin_size_t        size_t;
                                   ^
    4 errors generated.
    make[4]: *** [Makefile:6719: checkheader_vlc_media_library_h] Error 1