opengl: sampler: fix swizzle components
The GLSL allows three different swizzling:
 - .rgba
 - .stuv
 - .xyzw

However, they are not allowed to be mixed together:

    ERROR: 0:8: Inconsistent component characters in swizzle 'xa'
    ERROR: 0:10: Use of undeclared identifier 'pixel'
    ERROR: 0:11: Use of undeclared identifier 'result'

Fix the swizzling to w instead of a.