d3d11: Avoid -Wint-conversion errors
Clang 15 made "incompatible pointer to integer conversion" an error
instead of a plain warning. This fixes errors like these:

d3d11va.c:426:29: error: incompatible integer to pointer conversion assigning to 'ID3D11DeviceContext *' (aka 'struct ID3D11DeviceContext *') from 'int64_t' (aka 'long long') [-Wint-conversion]
    sys->d3d_dev.d3dcontext = var_InheritInteger(va, "winrt-d3dcontext");