qt: workaround for `undefined reference to `qt_version_tag'` error
KF6WindowSystem requires Qt6Gui, but not Qt6Core.
And Qt6Gui does not require Qt6Core.

The symbol `qt_version_tag` is available in Qt6Core.