Revert "Contrib: update upnp win32 patch"
This reverts commit 853a6c489c353ecd994bc73912139281d30ee0d4.

Breaks compilation with mingw-w64 3.2 :

libtool: compile:  x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I..
-I../upnp/inc -I./inc -I../threadutil/inc -I../ixml/inc -I./src/inc
-I/contrib/x86_64-w64-mingw32/include -DPTW32_STATIC_LIB
-DUPNP_STATIC_LIB -I/contrib/x86_64-w64-mingw32/include
-g -DUPNP_STATIC_LIB -DPTW32_STATIC_LIB -Os -Wall -c src/api/upnpapi.c
-o src/api/libupnp_la-upnpapi.o
src/api/upnpapi.c: In function 'UpnpGetIfInfo':
src/api/upnpapi.c:3214:2: error: unknown type name 'PIP_ADAPTER_ADDRESSES'
  PIP_ADAPTER_ADDRESSES adapts = NULL;
  ^