contrib: gnutls: fix 3.6 compilation with an older macOS SDK
Fixes this compilation error:
system/fastopen.c:134:9: error: 'connectx' is only available on macOS 10.11 or newer [-Werror,-Wunguarded-availability]
                ret = connectx(fd, &endpoints, SAE_ASSOCID_ANY, CONNECT_RESUME_ON_READ_WRITE | CONNECT_DATA_IDEMPOTENT, NULL, 0, NULL, NULL);
                      ^~~~~~~~
/Applications/Xcode9.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/socket.h:713:5:
note: 'connectx' has been marked as being introduced in macOS 10.11 here, but the deployment target is macOS 10.7.0

In this patch __builtin_available() is assumed to be avalaible in the toolchain
which is the case in our 3.0 and 4.0 toolchains. A cleaner patch should detect
it in configure.ac. But we can't do autoconf changes in gnutls as it never
works properly.

The OS values match exactly the values found in
https://opensource.apple.com/source/xnu/xnu-4570.41.2/bsd/sys/socket.h

(cherry picked from commit c4a23f4cd0e5370d1b5f6f8a6a9302b35c3a8ea4)

Signed-off-by: Steve Lhomme <robux4@ycbcr.xyz>