vlcrs-core: tracer: fix doctest
Doctests now requires the types from the current module to be imported
explicitely, which results in compilation errors currently:

    error[E0405]: cannot find trait `TracerCapability` in this scope
      --> src/rust/vlcrs-core/src/tracer/mod.rs:229:6
        |
    229 | impl TracerCapability for T {
        |      ^^^^^^^^^^^^^^^^ not found in this scope
        |
    help: consider importing this trait
        |
    228 + use vlcrs_core::tracer::TracerCapability;
        |

    error[E0425]: cannot find type `T` in this scope
      --> src/rust/vlcrs-core/src/tracer/mod.rs:229:27
        |
    229 | impl TracerCapability for T {
        |                           ^ not found in this scope

    error[E0425]: cannot find type `Trace` in this scope
      --> src/rust/vlcrs-core/src/tracer/mod.rs:230:29
        |
    230 |     fn trace(&self, trace: &Trace) {
        |                             ^^^^^ not found in this scope
        |
    help: consider importing this struct
        |
    228 + use vlcrs_core::tracer::Trace;
        |