contrib: projectM: Don't force building in C++98 mode
Instead patch the project to fix the error that was clang gave when
building in C+11 mode (which clang 6 does by default):

Renderer/VideoEcho.cpp:77:30: error: non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing]
  float pointsFlip[4][2] = {{-0.5*flipx, -0.5*flipy},

(cherry picked from commit e2ea86d8a21d5ddf63f9263aec401f0f8556e671)