gai_strerror: map missing Windows getaddrinfo/getnameinfo errors
gai_strerror() is called to get the string version of an error code returned by
vlc_getaddrinfo(), vlc_getnameinfo() or vlc_getaddrinfo_i11e(). In all
cases the value comes from an OS call. On Windows they return both EAI_* and a
lot of WSA errors [^1].

The strings come from src/win32/error.c.

[^1]: https://learn.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo#return-value

(cherry picked from commit fabc936116822567af28ed3a43012e2774779b03)
Signed-off-by: Steve Lhomme <robux4@ycbcr.xyz>