nvdec: Avoid including glext.h if glew.h has been included
glew.h and glext.h conflict due to two legacy and unfinished
extensions with conflicting declarations of the same function
name but with differing types (where one clearly is wrong and
never can have been used in that form).

See https://github.com/nigels-com/glew/pull/239 for upstream
discussion on how to fix this in glew and/or the OpenGL
extension registry.

This fixes build errors like these:
glext.h:12230:25: error: typedef redefinition with different types ('void (*)(GLenum, GLenum, GLint *)' (aka 'void (*)(unsigned int, unsigned int, int *)') vs 'void (*)(GLenum, GLenum, const GLint *)' (aka 'void (*)(unsigned int, unsigned int, const int *)'))
typedef void (APIENTRYP PFNGLGETFRAGMENTMATERIALIVSGIXPROC) (GLenum face, GLenum pname, GLint *params);
                        ^
glew.h:18744:28: note: previous definition is here
typedef void (GLAPIENTRY * PFNGLGETFRAGMENTMATERIALIVSGIXPROC) (GLenum face, GLenum pname, const GLint* data);