lua: Define LUA_COMPAT_APIINTCASTS for Lua >= 5.3.0 compatibility.
In Lua 5.3.0, luaL_checkint was deprecated.

This patch fixes this build error with Lua 5.3.0.

lua/demux.c: In function ‘vlclua_demux_peek’:
lua/demux.c:55:5: error: implicit declaration of function ‘luaL_checkint’ [-Werror=implicit-function-declaration]
     int n = luaL_checkint( L, 1 );
     ^

Signed-off-by: Vinson Lee <vlee@freedesktop.org>
Signed-off-by: Jean-Baptiste Kempf <jb@videolan.org>