tools: patch cmake 3.17 so it builds with a macOS 10.13 SDK
Avoid this link error:
[ 44%] Linking C executable curltest
Undefined symbols for architecture x86_64:
  "_SSLCopyALPNProtocols", referenced from:
      _sectransp_connect_step2 in libcmcurl.a(sectransp.c.o)
  "_SSLSetALPNProtocols", referenced from:
      _sectransp_connect_common in libcmcurl.a(sectransp.c.o)
ld: symbol(s) not found for architecture x86_64

This only happens in the 3.0 macOS CI.

(cherry picked from commit ab126f80d3aea19d85c8b91f361d646fab6f4560)

Signed-off-by: Steve Lhomme <robux4@ycbcr.xyz>