fsstorage: missing #include
-----
  CC       addons/fsstorage.lo
addons/fsstorage.c: In function 'WriteCatalog':
addons/fsstorage.c:543:5: error: implicit declaration of function 'getpid' [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors
make.exe[5]: *** [addons/fsstorage.lo] Error 1
-----

Signed-off-by: Jean-Baptiste Kempf <jb@videolan.org>