contrib: vncclient: Fix building for Windows with recent versions of Clang
This fixes errors like this with recent versions of Clang:

    libvncserver/src/libvncclient/tls_gnutls.c:161:32: error: incompatible pointer types passing 'gnutls_session_t *' (aka 'struct gnutls_session_int **') to parameter of type 'gnutls_session_t' (aka 'struct gnutls_session_int *'); dereference with * [-Wincompatible-pointer-types]
      161 |     gnutls_transport_set_errno(session, EAGAIN);
          |                                ^~~~~~~
          |                                *
    x86_64-w64-mingw32/include/gnutls/gnutls.h:2429:50: note: passing argument to parameter 'session' here
     2429 | void gnutls_transport_set_errno(gnutls_session_t session, int err);
          |

With different compilers, this would only be a warning, not an error,
but the mismatch would be fatal if ever executed.

This is a backport of commit 53b76ce9c8224b9dc9b566c018a07e9e96f2ce4c
from upstream.

While patching this project, also backport commit
9c68402d000486b7dee76b104fbb0109836c94f3 from upstream, fixing
another issue with the cmake build of this project.

(cherry picked from commit f575a4d79e86948e2024151f83fbbf82e6c165a2)
Signed-off-by: Steve Lhomme <robux4@ycbcr.xyz>