vlc_fixups: fix ssize_t not being defined
When compiling and not having writev/readv, the following error happens:

    make[2]: Entering directory '/home/janniaux/Projects/videolabs/vlc/build-tsan/compat'
      CC       strlcpy.lo
      CC       strnstr.lo
    In file included from ../config.h:952,
                     from ../../compat/strnstr.c:22:
    ../../include/vlc_fixups.h:232:1: error: unknown type name ‘ssize_t’; did you mean ‘size_t’?
      232 | ssize_t readv(int, const struct iovec *, int);
          | ^~~~~~~
          | size_t
    In file included from ../config.h:952,
                     from ../../compat/strlcpy.c:22:
    ../../include/vlc_fixups.h:232:1: error: unknown type name ‘ssize_t’; did you mean ‘size_t’?
      232 | ssize_t readv(int, const struct iovec *, int);
          | ^~~~~~~
          | size_t
    ../../include/vlc_fixups.h:237:1: error: unknown type name ‘ssize_t’; did you mean ‘size_t’?
      237 | ssize_t writev(int, const struct iovec *, int);
          | ^~~~~~~
          | size_t
    ../../include/vlc_fixups.h:237:1: error: unknown type name ‘ssize_t’; did you mean ‘size_t’?
      237 | ssize_t writev(int, const struct iovec *, int);
          | ^~~~~~~
          | size_t
    make[2]: *** [Makefile:1531: strnstr.lo] Error 1