d3d11_adjust: Pass a non-const pointer to atomic_load
This fixes compilation with clang, which previously errored
out with this message:

error: address argument to atomic operation must be a pointer to non-const _Atomic
      type ('const atomic_int *' (aka 'const _Atomic(int) *') invalid)
    int level = atomic_load(&p_level->level);
                ^           ~~~~~~~~~~~~~~~

(cherry picked from commit c51613372b52f5ae6039be67191b4b511a35e798)