demux: adaptative: fix compilation on OS/2
-----
  CXX      demux/adaptative/plumbing/libadaptative_plugin_la-CommandsQueue.lo
In file included from f:/lang/gcc/usr/local492/include/c++/4.9.2/atomic:38:0,
                 from ../include/vlc_atomic.h:221,
                 from demux/adaptative/plumbing/CommandsQueue.hpp:29,
                 from demux/adaptative/plumbing/CommandsQueue.cpp:20:
f:/lang/gcc/usr/local492/include/c++/4.9.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from f:/lang/gcc/usr/local492/include/c++/4.9.2/atomic:41:0,
                 from ../include/vlc_atomic.h:221,
                 from demux/adaptative/plumbing/CommandsQueue.hpp:29,
                 from demux/adaptative/plumbing/CommandsQueue.cpp:20:
f:/lang/gcc/usr/local492/include/c++/4.9.2/bits/atomic_base.h:74:3: error: 'constexpr' does not name a type
   constexpr memory_order
   ^
...
-----

Signed-off-by: Jean-Baptiste Kempf <jb@videolan.org>