contrib: nfs: require gnutls
Without this patch, building vlc fails with:
"libnfs.so: undefined reference to gnutls_XXX"

(cherry picked from commit f6db0ac6acc9ca41def18a2758f7b3b27e0e7606)