configure: Try to add -Wno-incompatible-ms-struct if adding -mms-bitfields
This avoids warnings that are treated as errors by default when building
with clang - warnings like these:

In file included from modules/access/dcp/dcp.cpp:59:
In file included from contrib/x86_64-w64-mingw32/include/AS_DCP.h:88:
In file included from contrib/x86_64-w64-mingw32/include/KM_fileio.h:35:
contrib/x86_64-w64-mingw32/include/KM_util.h:48:11: error: ms_struct may not produce Microsoft-compatible layouts for classes with base classes or virtual functions [-Wincompatible-ms-struct]
    class IntPrinter : public std::string

(cherry picked from commit 89707bdde37c8b77a8cb4546166da53d4b8cc516)
Signed-off-by: Hugo Beauzée-Luyssen <hugo@beauzee.fr>