spatializer: switch to std::array for callback list
The double-brace initialization is need for now because of legacy C++
limitations that are fixed in more recent standard version, otherwise:

    ../../modules/audio_filter/spatializer/spatializer.cpp:132:1: error: too many initializers for ‘const std::array<{anonymous}::callback_s, 5>’
      132 | };
          | ^