bluray: Fix BD_EVENT_UO_MASK_CHANGED case
Building VLC with a libbluray version older than 0.8.1 results in a build
failure because the BD_EVENT_UO_MASK_CHANGED enum does not exist in those
older versions. This problem manifests itself in Ubuntu 14.04.

  CC       access/liblibbluray_plugin_la-bluray.lo
access/bluray.c: In function ‘blurayHandleEvent’:
access/bluray.c:1985:10: error: ‘BD_EVENT_UO_MASK_CHANGED’ undeclared (first use in this function)
     case BD_EVENT_UO_MASK_CHANGED:
          ^
access/bluray.c:1985:10: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [access/liblibbluray_plugin_la-bluray.lo] Error 1

Signed-off-by: Jean-Baptiste Kempf <jb@videolan.org>