glwin32: Don't return an error code from a void function
This fixes a compiler error with clang, present since ed9fe3b7:

glwin32.c:249:9: error: void function 'Manage' should not return a value [-Wreturn-type]
        return VLC_EGENERIC;
        ^      ~~~~~~~~~~~~

(cherry picked from commit 69bf49a1037522d1cd640fdcb5b32107db6e78aa)
Signed-off-by: Jean-Baptiste Kempf <jb@videolan.org>