sout: sdi: fix missing include
The header refers to a std::string while not actually including	the
C++ string class.  This manifests as the following error seen on OSX:

DBMSDIOutput.cpp:75:38: error: implicit instantiation undefined
template 'std::__1::basic_string<char, std::__1::char_traits<char>,
std::__1::allocator<char> >

Add in the missing header.

Signed-off-by: Devin Heitmueller <dheitmueller@ltnglobal.com>
Signed-off-by: Francois Cartegnie <fcvlcdev@free.fr>