vlcrs-core: convert: add missing qualification
std::from_utf8 is from std.
See https://doc.rust-lang.org/std/str/fn.from_utf8.html

    error[E0599]: no function or associated item named `from_utf8` found for type `str` in the current scope
    --> src/rust/vlcrs-core/src/convert.rs:62:18
    |
    62 |             str::from_utf8(self.to_bytes()).expect("Unexpected invalid UTF8 coming from VLC")
    |                  ^^^^^^^^^ function or associated item not found in `str`
    |
    help: you are looking for the module in `std`, not the primitive type
    |
    62 |             std::str::from_utf8(self.to_bytes()).expect("Unexpected invalid UTF8 coming from VLC")
    |             +++++