contrib: xcb: bump to version 1.14
The 1.14 is out since February 2020[¹].

Fixes compilation error such as:

  GEN      xproto.c
  File "$VLC/contrib/contrib-native/libxcb/src/./c_client.py", line 1937
    after_end_of_request = '(((char*)R) + R->length * 4)'
  TabError: inconsistent use of tabs and spaces in indentation

[^1]: https://lists.x.org/archives/xorg-announce/2020-February/003039.html