contrib: freetype: actually disable bzip2
Regression from d9c9482b253762312bcb5c0ab5043e34bb23575f.

This fixes linking on macOS with static Qt from contribs:

Undefined symbols for architecture x86_64:
  "_BZ2_bzDecompress", referenced from:
      _ft_bzip2_file_fill_output in libfreetype.a(ftbzip2.c.o)
  "_BZ2_bzDecompressEnd", referenced from:
      _ft_bzip2_stream_io in libfreetype.a(ftbzip2.c.o)
      _ft_bzip2_stream_close in libfreetype.a(ftbzip2.c.o)
  "_BZ2_bzDecompressInit", referenced from:
      _FT_Stream_OpenBzip2 in libfreetype.a(ftbzip2.c.o)
      _ft_bzip2_stream_io in libfreetype.a(ftbzip2.c.o)
ld: symbol(s) not found for architecture x86_64