projectM: Force building with a specific older C++ version
This fixes errors like these:

libprojectM/projectM.hpp:303:8: error: no template named 'auto_ptr' in namespace 'std'
  std::auto_ptr<Preset> m_activePreset;
  ~~~~~^

The std::auto_ptr type was deprecated in C++11 and removed in C++17.

The VLC C++ headers use C++11 features, so the only working
alternatives here are C++11 or C++14.

(cherry picked from commit 4100c227d052cf5f804acd67904f698e89946110)
Signed-off-by: Martin Storsjö <martin@martin.st>