meson: qt: add missing csdbuttonmodel sources
This was causing a link failure:

/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h:1590: undefined reference to `CSDButton::staticMetaObject'

It was recently added by 99ee50c5541f7def32fb6451c2f88eae0bdeb379.