vlcrs-core: convert: fix internal doctest
Doctests somehow actually requires what it references to be public now,
and pub(crate) elements are not accessible anymore, so the doctest is
failing to compile with the following error:

      error[E0599]: no method named `assume_valid` found for reference `&CStr` in the current scope
      --> src/rust/vlcrs-core/src/convert.rs:40:64
         |
      40 |     let trace: &str = unsafe { std::ffi::CStr::from_ptr(trace).assume_valid() };
         |                                                                ^^^^^^^^^^^^ method not found in `&CStr`