contrib: projectM: Force building with a specific older C++ version
This project uses std::auto_ptr, which was deprecated in C++11,
so stick to compiling in C++98 mode. (Either C++98, C++11 or
C++14 would work.)

This fixes building with newer compilers that default to C++17
if nothing is specified (which is the default since GCC 11
and Clang 16).

When building with Clang/libc++ 16 in C++17 mode, it fails with
errors like these:

<build>/projectM/Renderer/RenderItemDistanceMetric.hpp:20:46: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
class RenderItemDistanceMetric : public std::binary_function<const RenderItem*, const RenderItem*, double> {
                                        ~~~~~^~~~~~~~~~~~~~~

(The std::binary_function class is removed in C++17.)

(cherry picked from commit 3e29d7f67991e60c8830e3a551419f7b8663f4b3)
Signed-off-by: Martin Storsjö <martin@martin.st>