ncurses: disable string format warning
gcc claims c can be NULL but it cannot.

gui/ncurses.c:401:17: error: '%s' directive argument is null [-Werror=format-overflow=]
  401 |             if (asprintf(&tmp, "%s%c ", c, last ? ' ' : '|') == -1)
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~