vlcrs-macros: tests: fix dangerous_implicit_autorefs lint
Add explicit reference around raw pointer dereference used for
indexing since implicit autoref from a raw pointer dereference,
is now denied by newer Rust nightly.

Error from rustc:

      error: implicit autoref creates a reference to the dereference of a raw pointer
      --> src/rust/vlcrs-macros/tests/common/mod.rs:43:20
         |
      43 |         assert_eq!((*context).commands[(*context).command_cursor], opcode);
         |                    ^^-------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         |                      |
         |                      this raw pointer has type `*mut TestContext<T>`
         |
         = note: creating a reference requires the pointer target to be valid and imposes aliasing requirements
      note: autoref is being applied to this expression, resulting in: `&Vec<ModuleProperties>`
      --> src/rust/vlcrs-macros/tests/common/mod.rs:43:20
         |
      43 |         assert_eq!((*context).commands[(*context).command_cursor], opcode);
         |                    ^^^^^^^^^^^^^^^^^^^
         = note: `#[deny(dangerous_implicit_autorefs)]` on by default
      help: try using a raw pointer method instead; or if this reference is intentional, make it explicit
         |
      43 |         assert_eq!((&(*context).commands)[(*context).command_cursor], opcode);
         |                    ++                   +