Fix build error if strnstr is missing
Support for strnstr was added in
http://git.videolan.org/?p=vlc.git;a=commitdiff;h=4c1238c77239cdea38a44748f2800332818b6750

but for systems lacking it, it broke the build:

  CC       strnstr.lo
In file included from ../config.h:887:0,
                 from strnstr.c:22:
../include/vlc_fixups.h:157:45: error: unknown type name ‘size_t’
 char * strnstr (const char *, const char *, size_t);

This patch fixes the problem by adding strnstr to a list of other
functions to get size_t defined.

Bug was reported to trac:
https://trac.videolan.org/vlc/ticket/16767

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Rémi Denis-Courmont <remi@remlab.net>