os2: missing #include
-----
  CC       os2/specific.lo
os2/specific.c: In function 'IPCHelperThread':
os2/specific.c:57:5: error: implicit declaration of function 'pl_Get' [-Werror=implicit-function-declaration]
os2/specific.c:57:30: warning: initialization makes pointer from integer without a cast [enabled by default]
cc1: some warnings being treated as errors
-----

Signed-off-by: Francois Cartegnie <fcvlcdev@free.fr>