contrib: caca: force recognition of all sprint variants tested on Windows
The built-in in some mingw-w64 variants require linking for kernel32.

configure:18427: i686-w64-mingw32-gcc -o conftest.exe -D__MSVCRT_VERSION__=0x700 -D_WIN32_WINNT=0x0502 -DWINVER=0x0502  -I/home/videolan/vlc/contrib/i686-w64-mingw32/include -g -O0 -D__MSVCRT_VERSION__=0x700 -D_WIN32_WINNT=0x0502 -DWINVER=0x0502 -I/home/videolan/vlc/contrib/i686-w64-mingw32/include -DCACA_STATIC  -L/home/videolan/vlc/contrib/i686-w64-mingw32/lib  conftest.c  >&5
conftest.c:47:6: warning: conflicting types for built-in function 'vsnprintf'
 char vsnprintf ();
      ^~~~~~~~~
/opt/gcc-i686-w64-mingw32/lib/gcc/i686-w64-mingw32/6.4.0/../../../../i686-w64-mingw32/lib/../lib/libmsvcrt.a(lib32_libmsvcrt_extra_a-_vscprintf.o): In function `_mingw_get_msvcrt_handle':
/build/mingw-w64/mingw-w64-crt/build/../include/msvcrt.h:9: undefined reference to `_imp__GetModuleHandleW@4'
collect2: error: ld returned 1 exit status
configure:18427: $? = 1