qt: fix property `UpdateModel::explicitCheck` can not be reset from QML
By adding a workaround for QML engine bug where it prints the
error:

TypeError: Cannot assign to read-only property "explicitCheck"

This error is not correct, because although the property does
not have WRITE method, it has the RESET method. The docs state
that assigning a property `undefined` would call the RESET
method, but it does not happen if the property also does not
have WRITE method.