gai_strerror: remap Windows SDK EAI_NODATA to WSANO_DATA
Otherwise it's mapped to WSAHOST_NOT_FOUND which we already handle with EAI_NONAME.
And we wouldn't have a string for WSANO_DATA.

(cherry picked from commit 8f9d92fd5c4bc3ec35c92f80d13e3f27b3c6e2ea)
Signed-off-by: Steve Lhomme <robux4@ycbcr.xyz>