Revert "Fix windows build (undefined reference to gpg_error_*)"
LibVLC is not calling gpg_error functions anywhere. Linking gpg-error
causes problems with *correctly* built libgcrypt (e.g. incorrect
package dependencies).

This reverts commit f865a8169457c8fa934782974e1b21c534bf0744.