meson: fix OpenGL Windows build
Regression from 85c9ce94bb1d1f520aafb615b0e4189c2e47a9d0.

In file included from ../../../vlc/modules/video_filter/gladjust.c:33:
In file included from ../../../vlc/modules/video_output/opengl/gl_api.h:33:
../../../vlc/modules/video_output/opengl/gl_common.h:45:13: fatal error: 'GL/glew.h' file not found
   45 | #   include <GL/glew.h>
      |             ^~~~~~~~~~~
1 error generated.