contrib: gettext: Backport a gnulib patch to fix building on Clang 16
Clang 16 made implicit function pointer conversions in C an error
(which previously was only a warning).

This backports the following change from upstream gnulib
to the version of the files bundled in gettext:
https://git.savannah.gnu.org/cgit/gnulib.git/commit/lib/obstack.c?id=0cc39712803ade7b2d4b89c36b143dad72404063

This fixes errors like these:

    obstack.c:351:31: error: incompatible function pointer types initializing 'void (*)(void) __attribute__((noreturn))' with an expression of type 'void (void)' [-Wincompatible-function-pointer-types]
    __attribute_noreturn__ void (*obstack_alloc_failed_handler) (void)
                                  ^