demux: adaptive: fixup for commit b99bc394843b4967
error: ‘sscanf’ is not a member of ‘std’
        if (std::sscanf(line.c_str(), "%zx%n", &chunkLength, &end) < 1
            ^

Fix build with compilers which do not default to c++11 or later,
e.g. g++ < 6, clang++ up to and including 3.9.

Noticed during build for VLC-Android.

Signed-off-by: Francois Cartegnie <fcvlcdev@free.fr>