contrib: shout: drop obsolete bsd.patch
It was added to fix this FreeBSD 8 error:
sock.c:736: error: 'IPPROTO_IPV6' undeclared

The need for __BSD_VISIBLE was removed in:
https://github.com/freebsd/freebsd/commit/fcb67434842e8a1a8ba60a2607b55922d35887fb#diff-dab66d274da3dd4ba168b2ba7f3b4374

Which predates the last supported FreeBSD releases