gai_strerror: add declaration as its not defined in vlc_fixups.h
(cherry picked from commit 0c45a05b8748acd2b97218d8633c6fdcda89343f)
Signed-off-by: Steve Lhomme <robux4@ycbcr.xyz>