contrib: ffmpeg: use -Og in non optimized builds
It's better than -O0 in some cases, like clang on i686 that gives this error:

 In file included from libavcodec/h264_cabac.c:46:
libavcodec/x86/h264_cabac.c:66:9: error: inline assembly requires more registers than available
        "3:                                     \n\t"
        ^
1 error generated.
make[1]: *** [ffbuild/common.mak:59: libavcodec/h264_cabac.o] Error 1

(cherry picked from commit c20a10f06bd4f5469fcbe8616abcd64469efd09a)

Signed-off-by: Steve Lhomme <robux4@ycbcr.xyz>