vlc_fourcc: Fix regression introduced in 1ea223dff935004e110542a6894c8b22d602876d
VLC_CODEC_BGR555 should be defined on BE architectures as VLC_CODEC_BGR555BE and not VLC_CODEC_BGR565BE

Fixes build failure:

video_filter/blend.cpp: In constructor ‘{anonymous}::CPictureRGB16::CPictureRGB16(const {anonymous}::CPicture&)’:
video_filter/blend.cpp:357:9: error: duplicate case value
  357 |         case VLC_CODEC_BGR555:
      |         ^~~~
video_filter/blend.cpp:347:9: note: previously used here
  347 |         case VLC_CODEC_BGR565:
      |         ^~~~
video_filter/blend.cpp: In constructor ‘{anonymous}::convertRgbToRgbSmall::convertRgbToRgbSmall(const video_format_t*, const video_format_t*)’:
video_filter/blend.cpp:506:9: error: duplicate case value
  506 |         case VLC_CODEC_BGR555:
      |         ^~~~
video_filter/blend.cpp:496:9: note: previously used here
  496 |         case VLC_CODEC_BGR565:
      |         ^~~~