Revert "opengl: egl_gbm: use DRM_DIR_NAME for path"
This reverts commit 6218609ae411b6289174521a012e82376329109f.

This broke the build:

../../modules/video_output/opengl/egl_display_gbm.c: In function ‘OpenDeviceFd’:
../../modules/video_output/opengl/egl_display_gbm.c:72:26: error: expected ‘}’ before ‘DRM_RENDER_MINOR_NAME’
   72 |         DRM_DIR_NAME "/" DRM_RENDER_MINOR_NAME "128",
      |                          ^~~~~~~~~~~~~~~~~~~~~
../../modules/video_output/opengl/egl_display_gbm.c:71:53: note: to match this ‘{’
   71 |     static const char *default_drm_device_paths[] = {
      |                                                     ^